export interface CharacterData {
  character: string;
  romaji: string;
  example: string;
  exampleRomaji: string;
  exampleMeaning: string;
}

export const hiraganaBasic: CharacterData[] = [
  { character: "あ", romaji: "a", example: "あさ", exampleRomaji: "asa", exampleMeaning: "morning" },
  { character: "い", romaji: "i", example: "いぬ", exampleRomaji: "inu", exampleMeaning: "dog" },
  { character: "う", romaji: "u", example: "うみ", exampleRomaji: "umi", exampleMeaning: "sea" },
  { character: "え", romaji: "e", example: "えき", exampleRomaji: "eki", exampleMeaning: "station" },
  { character: "お", romaji: "o", example: "おちゃ", exampleRomaji: "ocha", exampleMeaning: "tea" },
  { character: "か", romaji: "ka", example: "かさ", exampleRomaji: "kasa", exampleMeaning: "umbrella" },
  { character: "き", romaji: "ki", example: "きつね", exampleRomaji: "kitsune", exampleMeaning: "fox" },
  { character: "く", romaji: "ku", example: "くも", exampleRomaji: "kumo", exampleMeaning: "cloud" },
  { character: "け", romaji: "ke", example: "けさ", exampleRomaji: "kesa", exampleMeaning: "this morning" },
  { character: "こ", romaji: "ko", example: "こおり", exampleRomaji: "kouri", exampleMeaning: "ice" },
  { character: "さ", romaji: "sa", example: "さくら", exampleRomaji: "sakura", exampleMeaning: "cherry blossom" },
  { character: "し", romaji: "shi", example: "しか", exampleRomaji: "shika", exampleMeaning: "deer" },
  { character: "す", romaji: "su", example: "すし", exampleRomaji: "sushi", exampleMeaning: "sushi" },
  { character: "せ", romaji: "se", example: "せんせい", exampleRomaji: "sensei", exampleMeaning: "teacher" },
  { character: "そ", romaji: "so", example: "そら", exampleRomaji: "sora", exampleMeaning: "sky" },
  { character: "た", romaji: "ta", example: "たいやき", exampleRomaji: "taiyaki", exampleMeaning: "fish cake" },
  { character: "ち", romaji: "chi", example: "ちきゅう", exampleRomaji: "chikyuu", exampleMeaning: "earth" },
  { character: "つ", romaji: "tsu", example: "つき", exampleRomaji: "tsuki", exampleMeaning: "moon" },
  { character: "て", romaji: "te", example: "てんき", exampleRomaji: "tenki", exampleMeaning: "weather" },
  { character: "と", romaji: "to", example: "とり", exampleRomaji: "tori", exampleMeaning: "bird" },
  { character: "な", romaji: "na", example: "なつ", exampleRomaji: "natsu", exampleMeaning: "summer" },
  { character: "に", romaji: "ni", example: "にわとり", exampleRomaji: "niwatori", exampleMeaning: "chicken" },
  { character: "ぬ", romaji: "nu", example: "ぬいぐるみ", exampleRomaji: "nuigurumi", exampleMeaning: "stuffed toy" },
  { character: "ね", romaji: "ne", example: "ねこ", exampleRomaji: "neko", exampleMeaning: "cat" },
  { character: "の", romaji: "no", example: "のり", exampleRomaji: "nori", exampleMeaning: "seaweed" },
  { character: "は", romaji: "ha", example: "はな", exampleRomaji: "hana", exampleMeaning: "flower" },
  { character: "ひ", romaji: "hi", example: "ひかり", exampleRomaji: "hikari", exampleMeaning: "light" },
  { character: "ふ", romaji: "fu", example: "ふじさん", exampleRomaji: "fujisan", exampleMeaning: "Mt. Fuji" },
  { character: "へ", romaji: "he", example: "へいわ", exampleRomaji: "heiwa", exampleMeaning: "peace" },
  { character: "ほ", romaji: "ho", example: "ほし", exampleRomaji: "hoshi", exampleMeaning: "star" },
  { character: "ま", romaji: "ma", example: "まつり", exampleRomaji: "matsuri", exampleMeaning: "festival" },
  { character: "み", romaji: "mi", example: "みず", exampleRomaji: "mizu", exampleMeaning: "water" },
  { character: "む", romaji: "mu", example: "むし", exampleRomaji: "mushi", exampleMeaning: "bug" },
  { character: "め", romaji: "me", example: "めがね", exampleRomaji: "megane", exampleMeaning: "glasses" },
  { character: "も", romaji: "mo", example: "もみじ", exampleRomaji: "momiji", exampleMeaning: "maple leaf" },
  { character: "や", romaji: "ya", example: "やま", exampleRomaji: "yama", exampleMeaning: "mountain" },
  { character: "ゆ", romaji: "yu", example: "ゆき", exampleRomaji: "yuki", exampleMeaning: "snow" },
  { character: "よ", romaji: "yo", example: "よる", exampleRomaji: "yoru", exampleMeaning: "night" },
  { character: "ら", romaji: "ra", example: "らくだ", exampleRomaji: "rakuda", exampleMeaning: "camel" },
  { character: "り", romaji: "ri", example: "りんご", exampleRomaji: "ringo", exampleMeaning: "apple" },
  { character: "る", romaji: "ru", example: "るす", exampleRomaji: "rusu", exampleMeaning: "not at home" },
  { character: "れ", romaji: "re", example: "れきし", exampleRomaji: "rekishi", exampleMeaning: "history" },
  { character: "ろ", romaji: "ro", example: "ろうそく", exampleRomaji: "rousoku", exampleMeaning: "candle" },
  { character: "わ", romaji: "wa", example: "わに", exampleRomaji: "wani", exampleMeaning: "crocodile" },
  { character: "を", romaji: "wo", example: "を (object)", exampleRomaji: "wo", exampleMeaning: "object marker" },
  { character: "ん", romaji: "n", example: "おんせん", exampleRomaji: "onsen", exampleMeaning: "hot spring" },
];

export const hiraganaDakuten: CharacterData[] = [
  { character: "が", romaji: "ga", example: "がっこう", exampleRomaji: "gakkou", exampleMeaning: "school" },
  { character: "ぎ", romaji: "gi", example: "ぎんこう", exampleRomaji: "ginkou", exampleMeaning: "bank" },
  { character: "ぐ", romaji: "gu", example: "ぐあい", exampleRomaji: "guai", exampleMeaning: "condition" },
  { character: "げ", romaji: "ge", example: "げんき", exampleRomaji: "genki", exampleMeaning: "energetic" },
  { character: "ご", romaji: "go", example: "ごはん", exampleRomaji: "gohan", exampleMeaning: "rice/meal" },
  { character: "ざ", romaji: "za", example: "ざる", exampleRomaji: "zaru", exampleMeaning: "basket" },
  { character: "じ", romaji: "ji", example: "じかん", exampleRomaji: "jikan", exampleMeaning: "time" },
  { character: "ず", romaji: "zu", example: "ずつき", exampleRomaji: "zutsuki", exampleMeaning: "headbutt" },
  { character: "ぜ", romaji: "ze", example: "ぜんぶ", exampleRomaji: "zenbu", exampleMeaning: "all" },
  { character: "ぞ", romaji: "zo", example: "ぞう", exampleRomaji: "zou", exampleMeaning: "elephant" },
  { character: "だ", romaji: "da", example: "だいち", exampleRomaji: "daichi", exampleMeaning: "earth/ground" },
  { character: "ぢ", romaji: "di", example: "ぢゃがいも", exampleRomaji: "jagaimo", exampleMeaning: "potato" },
  { character: "づ", romaji: "du", example: "づけ", exampleRomaji: "zuke", exampleMeaning: "pickled" },
  { character: "で", romaji: "de", example: "でんしゃ", exampleRomaji: "densha", exampleMeaning: "train" },
  { character: "ど", romaji: "do", example: "どうぶつ", exampleRomaji: "doubutsu", exampleMeaning: "animal" },
  { character: "ば", romaji: "ba", example: "ばら", exampleRomaji: "bara", exampleMeaning: "rose" },
  { character: "び", romaji: "bi", example: "びょういん", exampleRomaji: "byouin", exampleMeaning: "hospital" },
  { character: "ぶ", romaji: "bu", example: "ぶどう", exampleRomaji: "budou", exampleMeaning: "grapes" },
  { character: "べ", romaji: "be", example: "べんきょう", exampleRomaji: "benkyou", exampleMeaning: "study" },
  { character: "ぼ", romaji: "bo", example: "ぼうし", exampleRomaji: "boushi", exampleMeaning: "hat" },
  { character: "ぱ", romaji: "pa", example: "ぱんつ", exampleRomaji: "pantsu", exampleMeaning: "pants" },
  { character: "ぴ", romaji: "pi", example: "ぴかぴか", exampleRomaji: "pikapika", exampleMeaning: "sparkling" },
  { character: "ぷ", romaji: "pu", example: "ぷりん", exampleRomaji: "purin", exampleMeaning: "pudding" },
  { character: "ぺ", romaji: "pe", example: "ぺんぎん", exampleRomaji: "pengin", exampleMeaning: "penguin" },
  { character: "ぽ", romaji: "po", example: "ぽっきり", exampleRomaji: "pokkiri", exampleMeaning: "exactly" },
];

export const allHiragana = [...hiraganaBasic, ...hiraganaDakuten];
