import type { CharacterData } from "./hiragana";

export const katakanaBasic: CharacterData[] = [
  { character: "ア", romaji: "a", example: "アイス", exampleRomaji: "aisu", exampleMeaning: "ice cream" },
  { character: "イ", romaji: "i", example: "イルカ", exampleRomaji: "iruka", exampleMeaning: "dolphin" },
  { character: "ウ", romaji: "u", example: "ウサギ", exampleRomaji: "usagi", exampleMeaning: "rabbit" },
  { character: "エ", romaji: "e", example: "エビ", exampleRomaji: "ebi", exampleMeaning: "shrimp" },
  { character: "オ", romaji: "o", example: "オニ", exampleRomaji: "oni", exampleMeaning: "demon" },
  { character: "カ", romaji: "ka", example: "カメラ", exampleRomaji: "kamera", exampleMeaning: "camera" },
  { character: "キ", romaji: "ki", example: "キリン", exampleRomaji: "kirin", exampleMeaning: "giraffe" },
  { character: "ク", romaji: "ku", example: "クリスマス", exampleRomaji: "kurisumasu", exampleMeaning: "Christmas" },
  { character: "ケ", romaji: "ke", example: "ケーキ", exampleRomaji: "keeki", exampleMeaning: "cake" },
  { character: "コ", romaji: "ko", example: "コーヒー", exampleRomaji: "koohii", exampleMeaning: "coffee" },
  { character: "サ", romaji: "sa", example: "サッカー", exampleRomaji: "sakkaa", exampleMeaning: "soccer" },
  { character: "シ", romaji: "shi", example: "シャツ", exampleRomaji: "shatsu", exampleMeaning: "shirt" },
  { character: "ス", romaji: "su", example: "スイカ", exampleRomaji: "suika", exampleMeaning: "watermelon" },
  { character: "セ", romaji: "se", example: "セーター", exampleRomaji: "seetaa", exampleMeaning: "sweater" },
  { character: "ソ", romaji: "so", example: "ソフト", exampleRomaji: "sofuto", exampleMeaning: "soft" },
  { character: "タ", romaji: "ta", example: "タクシー", exampleRomaji: "takushii", exampleMeaning: "taxi" },
  { character: "チ", romaji: "chi", example: "チーズ", exampleRomaji: "chiizu", exampleMeaning: "cheese" },
  { character: "ツ", romaji: "tsu", example: "ツナ", exampleRomaji: "tsuna", exampleMeaning: "tuna" },
  { character: "テ", romaji: "te", example: "テレビ", exampleRomaji: "terebi", exampleMeaning: "TV" },
  { character: "ト", romaji: "to", example: "トマト", exampleRomaji: "tomato", exampleMeaning: "tomato" },
  { character: "ナ", romaji: "na", example: "ナイフ", exampleRomaji: "naifu", exampleMeaning: "knife" },
  { character: "ニ", romaji: "ni", example: "ニワトリ", exampleRomaji: "niwatori", exampleMeaning: "chicken" },
  { character: "ヌ", romaji: "nu", example: "ヌイグルミ", exampleRomaji: "nuigurumi", exampleMeaning: "stuffed toy" },
  { character: "ネ", romaji: "ne", example: "ネクタイ", exampleRomaji: "nekutai", exampleMeaning: "necktie" },
  { character: "ノ", romaji: "no", example: "ノート", exampleRomaji: "nooto", exampleMeaning: "notebook" },
  { character: "ハ", romaji: "ha", example: "ハンバーガー", exampleRomaji: "hanbaagaa", exampleMeaning: "hamburger" },
  { character: "ヒ", romaji: "hi", example: "ヒーロー", exampleRomaji: "hiiroo", exampleMeaning: "hero" },
  { character: "フ", romaji: "fu", example: "フルーツ", exampleRomaji: "furuutsu", exampleMeaning: "fruit" },
  { character: "ヘ", romaji: "he", example: "ヘリコプター", exampleRomaji: "herikoputaa", exampleMeaning: "helicopter" },
  { character: "ホ", romaji: "ho", example: "ホテル", exampleRomaji: "hoteru", exampleMeaning: "hotel" },
  { character: "マ", romaji: "ma", example: "マンガ", exampleRomaji: "manga", exampleMeaning: "manga" },
  { character: "ミ", romaji: "mi", example: "ミルク", exampleRomaji: "miruku", exampleMeaning: "milk" },
  { character: "ム", romaji: "mu", example: "ムービー", exampleRomaji: "muubii", exampleMeaning: "movie" },
  { character: "メ", romaji: "me", example: "メロン", exampleRomaji: "meron", exampleMeaning: "melon" },
  { character: "モ", romaji: "mo", example: "モモ", exampleRomaji: "momo", exampleMeaning: "peach" },
  { character: "ヤ", romaji: "ya", example: "ヤギ", exampleRomaji: "yagi", exampleMeaning: "goat" },
  { character: "ユ", romaji: "yu", example: "ユニコーン", exampleRomaji: "yunikoon", exampleMeaning: "unicorn" },
  { character: "ヨ", romaji: "yo", example: "ヨーヨー", exampleRomaji: "yooyoo", exampleMeaning: "yo-yo" },
  { character: "ラ", romaji: "ra", example: "ラジオ", exampleRomaji: "rajio", exampleMeaning: "radio" },
  { character: "リ", romaji: "ri", example: "リス", exampleRomaji: "risu", exampleMeaning: "squirrel" },
  { character: "ル", romaji: "ru", example: "ルール", exampleRomaji: "ruuru", exampleMeaning: "rule" },
  { character: "レ", romaji: "re", example: "レモン", exampleRomaji: "remon", exampleMeaning: "lemon" },
  { character: "ロ", romaji: "ro", example: "ロボット", exampleRomaji: "robotto", exampleMeaning: "robot" },
  { character: "ワ", romaji: "wa", example: "ワニ", exampleRomaji: "wani", exampleMeaning: "crocodile" },
  { character: "ヲ", romaji: "wo", example: "ヲ (object)", exampleRomaji: "wo", exampleMeaning: "object marker" },
  { character: "ン", romaji: "n", example: "サンドイッチ", exampleRomaji: "sandoitchi", exampleMeaning: "sandwich" },
];

export const allKatakana = [...katakanaBasic];
